spring:
  application:
    name: order-service

  profiles:
    active: dev

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:3310/eureka

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

  tracing:
    sampling:
      probability: 1.0